#' Cloze probabilities from the Provo Corpus.
#'
#' A dataset containing the .. reference
#'
#' @format A data frame with 2730 rows and 16 variables:
#'
#' * `word_unique_id`: DESCRIPTION
#' * `text_id`: DESCRIPTION
#' * `word_n`: DESCRIPTION
#' * `word`: DESCRIPTION
#' * `word_cleaned`: DESCRIPTION
#' * `word_length`: DESCRIPTION
#' * `total_response_count`: DESCRIPTION
#' * `cp`: DESCRIPTION
#' * `modal_response`: DESCRIPTION
#' * `pos_claws`: DESCRIPTION
#' * `word_content_or_function`: DESCRIPTION
#' * `word_pos`: DESCRIPTION
#' * `pos_cp`: DESCRIPTION
#' * `lsa_context_score`: DESCRIPTION
#' * `lsa_response_match_score`: DESCRIPTION
#' * `text`: DESCRIPTION
#'
##' @family datasets
#'
#' @source \url{https://osf.io/sjefs//}
"data_provo_cloze"


#' Enriched  stimuli of \insertCite{Frank2013;textual}{pangoling} data
#'
#' A dataset containing the stimuli used in \insertCite{Frank2013;textual}{pangoling}. It is enriched with the estimates of surprisal and entropy reduction of \insertCite{Frank2013a;textual}{pangoling}
#'
#' As in the original dataset part-of-speech tags were generated by Tsuruoka & Tsujii's (2005) automatic tagger, and were corrected by hand (in accordance with the Penn Treebank part-of-speech  guidelines; Santorini, 1991); Punctuation marks receive their own tag, and clitics are split into two tags (e.g., "doesn't" is tagged "VBZ RB")
#'
#' @format A data frame with  rows and  variables:
#'
#' * `sent_id`: The sentence unique id.
#' * `sentence`: The sentence, as a single string
#' * `question`: Comprehension question (or hyphen if no question)
#' * `answer`: Correct answer to comprehension question (or hyphen if no question)
#' * `pos`: String of part-of-speech tags (Penn Treebank style)
#' * `word_n`: Position of the word in the sentence
#' * `word`: Presented word
#' * `surprisal_1`-`surprisal_10`: Surprisal estimate at ten points (x=1 to x=10) during network training.
#' * `deltaH1_1`-`deltaH4_10`: Entropy-reduction estimate at ten points during network training, with lookahead distance n.
#' @family datasets
#' @seealso [data_frank2013_spr_complete] for the associated self-paced reading data, [data_frank2013_spr] for a cleaned version of that dataaset,  [data_frank2013_et_fix] for the eye-tracking version of this dataset with the fixation information, and [data_frank2013_et_rt] for a preprocessed eye-tracking dataset.
#
#' @source \url{https://osf.io/sjefs//}
"data_frank2013_stimuli"


##' Self-paced reading data of \insertCite{Frank2013;textual}{pangoling}
#'
#' A dataset containing the self-paced reading data of \insertCite{Frank2013;textual}{pangoling}. Notice that after collecting the self-paced-reading data, three typos were found:
#' sentence 43  : "Scott" was "Sott"
#' sentence 269 : "at" was "that"
#' sentence 337 : "Margaret" was "Margeret"
#'
#' @format A data frame with  rows and  variables:
#'
#' * `subj`: Subject
#' * `sent_id`: Sentence unique id.
#' * `sent_n`: Position of sentence in presentation sequence
#' * `answer_time`: Time in msec between question presentation and response, or NaN if there was no question
#' * `word_n`: Position of the word in the sentence
#' * `word`: Presented word
#' * `RT`: Time in msec between word presentation and key press
#' * `acc_comprehension`: Correctness of response to comprehension question
#' * `age`: Subject's age in years
#' * `age_en`: Age at which subject began learning English (0 for native speakers)
#' * `sex`: Subject's sex (f/m)
#' * `hand`: Subject's handedness (r/l)
#' * `correct_perc`: Fraction of correct responses to comprehension questions.
#' * `typo`: Whether there is a typo in the word.
#'
#' @family datasets
#' @seealso [data_frank2013_stimuli] for the enriched stimuli,  [data_frank2013_spr] for a cleaned version of this dataset,  [data_frank2013_et_fix] for the eye-tracking version of this dataset with the fixation information, and [data_frank2013_et] for a preprocessed eye-tracking dataset.
"data_frank2013_spr_complete"


##' Cleaned self-paced reading data of \insertCite{Frank2013;textual}{pangoling}
#'
#' A cleaned version of dataset ["data_frank2013_spr_complete"]: No sentences with typos, only native speakers, and subjects with accuracy over 0.8.
#'
#' @family datasets
#' @seealso [data_frank2013_stimuli] for the enriched stimuli,  [data_frank2013_spr_complete] for the complete version of this dataset, [data_frank2013_et_fix] for the eye-tracking version of this dataset with the fixation information, and [data_frank2013_et_rt] for a preprocessed eye-tracking dataset.
"data_frank2013_spr"



#' Eye-tracking data of \insertCite{Frank2013;textual}{pangoling}
#'
##' Eye-tracking reading data of \insertCite{Frank2013;textual}{pangoling}
#
#'
#' @format A data frame with `r nrow(data_frank2013_et_rt)` rows and `r ncol(data_frank2013_et_rt)` columns:
#'
#' * `subj`: Subject
#' * `sent_id`: Sentence unique id.
#' * `sent_n`: Position of sentence in presentation sequence
#' * `answer_time`: Time in msec between question presentation and response, or NaN if there was no question
#' * `acc_comprehension`: Whether the answer is correct or not
#' * `word_n`: Position of the word in the sentence
#' * `word`: Presented word
#' * `RTfirstfix`: First fixation time on current word (or 0 if word not fixated)
#' * `RTfirstpass`: First-pass reading time (total fixation time on current word before first fixation on any other word)
#' * `RTrightbound`: Right-bounded reading time (total fixation time on current word before first fixation on any word to the right)
#' * `RTgopast`: Go-past reading time (total fixation time from first fixation on current word up to first fixation on any word to the right)
#' @family datasets
#' @seealso [data_frank2013_stimuli] for the enriched stimuli,  [data_frank2013_spr_complete] for the complete version of this dataset, [data_frank2013_spr] for a "cleaned" version of the self-paced reading data, and [data_frank2013_et_fix] for the raw fixation of this eye-tracking dataset.
"data_frank2013_et_rt"


#' Fixations positions of the eye-tracking data of \insertCite{Frank2013;textual}{pangoling}
#'
#' Fixations positions of the eye-tracking  data of \insertCite{Frank2013;textual}{pangoling}.
#'
#' As in the original dataset: "Within each sentence, fixations are listed in the order in which they occurred. If any fixation during sentence presentation was registered as being outside the display bounds, this was regarded as a tracking error and no data is presented for that sentence. The letter and word position are NaN if gaze_y is outside the range (300,475) because that was considered too far above or below the presented sentence."
#'
#' @format A data frame:
#'
#' * `subj`: Subject
#' * `sent_id`: Sentence unique id.
#' * `gaze_x`: Horizontal pixel coordinate of fixation location (0 = left edge; 39 = left margin; 1024 = right edge) Each letter (including space and punctuation) was 14 pixels wide.
#' * `gaze_y`: Vertical pixal coordinate of fixation location (0 = top of display; 768 = bottom of display)
#' * `fix_duration`: Duration of fixation in msec
#' * `letter_n`: Fixated letter position in sentence (including spaces), even if the fixation was to the left of the left margin or to the right of the last letter. Position 0 is directly to the left of the first letter.
#' * `word_n`: Position of the word in the sentence
#' * `word`: Presented word
#' * `blink`: Indicates whether a blink was detected directly 'before' or 'after' the current fixation (or 'both' before and after).
#' @seealso  [data_frank2013_stimuli] for the enriched stimuli, [data_frank2013_spr_complete] for the associated self-paced reading data, [data_frank2013_spr] for a cleaned version of that dataaset,  and [data_frank2013_et_rt] for a preprocessed this dataset.
"data_frank2013_et_fix"
